### ISSUE TITLE
Can not find files in ’cell_rep’ folder

### ISSUE THREAD

**Issue by yunshanglzy** [reiniuslab/Lentini_XCU_in_vivo#2]
I hope this message finds you well. I am writing to inquire about the availability of certain files within the **’cell_rep'** folder,  required for the **’R/load_data_cellrep.R'** process. I have searched extensively within the **E-MTAB-9324, E-MTAB-10709, and E-MTAB-10714** datasets but have been unable to locate these files.

I would greatly appreciate any assistance you can provide in accessing these datasets. Could you kindly advise me on the appropriate steps to take to obtain them? Your help would be most appreciated.

**Comment by ALentini** [comment]
Hey, thanks for getting in touch. The data is from a previously published study with accession "GSE109071" but we have now uploaded the data into the repository under the "cell_rep" folder

**Comment by ALentini** [comment]
Hey, thanks for getting in touch. The data is from a previously published study with accession "GSE109071" but we have now uploaded the data into the repository under the "cell_rep" folder

**Comment by yunshanglzy** [comment]
Thank you very much for your assistance. Your help has proven to be immensely valuable to me！
